display err msg in a popup
digimarc-corp/c2pa-content-credentials-extension pull request #35
Opened 2024-01-08 16:19 UTC by PercheEtienne

2024-01-09 10:15 UTC, clementh59 approved these changes

2024-01-09 10:55 UTC, domguinard requested changes
Great work but could we change the UX to show the CR pop up directly when clicking "Verify Content Credentials?

2024-01-09 10:59 UTC, domguinard requested changes

2024-01-09 10:59 UTC, domguinard commented on content.js
> +        displayError('No images found within the current element.');
```suggestion
        displayError('Unable to locate an image to verify.');
```

2024-01-10 15:45 UTC, PercheEtienne commented
> Great work but could we change the UX to show the CR pop up directly when clicking "Verify Content Credentials?

As discussed, we would need to update our fork of the c2pa-wc, so this is on hold

2024-01-10 15:47 UTC, merged